import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { runBackgen } from "../utils/run-backgen.js";

/**
 * Register the generate_seed tool on the MCP server.
 * Generates a database seed file for populating a resource with development data.
 */
export function generateSeedTool(server: McpServer) {
  server.tool(
    "generate_seed",
    "Creates a database seed file for a resource — a script that inserts realistic development data into your database so you don't manually populate tables while building features. The seed file is ORM-aware: it outputs to prisma/seeds/<resource>.ts for Prisma, db/seeds/<resource>.ts for Drizzle, or seeds/<resource>.ts for Mongoose. Each seed record uses faker-generated realistic values matching the resource's field types. Run generate_resource first for the resource you want to seed. After generating, you run the seed via 'npm run seed' in the project directory to insert the data. Use count to control how many records to generate — 10 is fine for development, 50-100 for load testing or demo environments. Maximum 1000.",
    {
      resource: z
        .string()
        .regex(/^[A-Z][a-zA-Z0-9]*$/)
        .describe("Resource name in PascalCase — must start with an uppercase letter. Must match an existing resource generated by generate_resource. Examples: 'Product', 'User', 'Appointment'."),
      count: z
        .number()
        .int()
        .min(1)
        .max(1000)
        .default(10)
        .describe("Number of seed records to generate. Use 5-10 for quick development setups where you just need sample data. Use 50-100 for demo environments, load testing, or populating dropdowns with realistic options. Max 1000."),
      dir: z
        .string()
        .optional()
        .describe("Absolute or relative path to the BackGen-generated project directory. Defaults to the current working directory. Example: '/home/user/projects/my-api'."),
    },
    async ({ resource, count, dir }) => {
      try {
        const output = runBackgen(["generate", "seed", resource, "--count", String(count)], dir);
        return {
          content: [
            {
              type: "text",
              text: [
                `✅ Seed data for "${resource}" generated (${count} records).`,
                "",
                "📋 Next step — run the seed:",
                `  cd ${dir || "your-project"} && npm run seed`,
                "",
                output,
              ].join("\n"),
            },
          ],
        };
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        return {
          content: [{ type: "text", text: `❌ Failed: ${message}` }],
          isError: true,
        };
      }
    }
  );
}
