import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { runBackgen } from "../utils/run-backgen.js";

/**
 * Register the generate_factory tool on the MCP server.
 * Generates a test factory for creating resource instances in tests.
 */
export function generateFactoryTool(server: McpServer) {
  server.tool(
    "generate_factory",
    "Creates a test factory file for a resource — a reusable builder that generates valid resource instances with sensible defaults for writing tests. Factories let you create test data in one line (e.g. createProduct({ name: 'Widget' })) instead of manually constructing full objects with required fields, timestamps, and relations every time. The generated factory is ORM-aware: it uses the same schema as your generated resource. Factories are written to src/factories/<resource>.factory.ts and use the faker library for realistic default values. Run generate_resource for a resource first — the factory matches its fields. Only PascalCase resource names are valid (e.g. 'Product', not 'product').",
    {
      resource: z
        .string()
        .regex(/^[A-Z][a-zA-Z0-9]*$/)
        .describe("Resource name in PascalCase — must start with an uppercase letter. Examples: 'Product', 'User', 'Appointment'. Must match an existing resource generated by generate_resource."),
      dir: z
        .string()
        .optional()
        .describe("Absolute or relative path to the BackGen-generated project directory. Defaults to the current working directory. Example: '/home/user/projects/my-api'."),
    },
    async ({ resource, dir }) => {
      try {
        const output = runBackgen(["generate", "factory", resource], dir);
        return {
          content: [
            {
              type: "text",
              text: [
                `✅ Factory for "${resource}" generated.`,
                "",
                `📁 File: src/factories/${resource.toLowerCase()}.factory.ts`,
                "",
                "📋 Usage in tests:",
                `  import { create${resource} } from "../factories/${resource.toLowerCase()}.factory.js";`,
                "",
                "  // Create with defaults (faker-generated realistic data):",
                `  const item = await create${resource}();`,
                "",
                "  // Override specific fields:",
                `  const item = await create${resource}({ name: "Custom Name" });`,
                "",
                output,
              ].join("\n"),
            },
          ],
        };
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        return {
          content: [{ type: "text", text: `❌ Failed: ${message}` }],
          isError: true,
        };
      }
    }
  );
}
