import chalk from "chalk";
import * as fs from "fs/promises";
import * as path from "path";

// ── Types ──────────────────────────────────────────────────────

interface OpenAPIDoc {
  openapi?: string;
  info?: { title?: string; version?: string };
  paths?: Record<string, unknown>;
  components?: {
    schemas?: Record<string, OpenAPISchema>;
  };
  definitions?: Record<string, OpenAPISchema>; // Swagger 2.0
}

interface OpenAPISchema {
  type?: string;
  properties?: Record<string, OpenAPIProperty>;
  required?: string[];
  allOf?: OpenAPISchema[];
  $ref?: string;
  description?: string;
}

interface OpenAPIProperty {
  type?: string;
  format?: string;
  $ref?: string;
  items?: { $ref?: string; type?: string };
  description?: string;
  nullable?: boolean;
  enum?: unknown[];
}

// ── Helpers ────────────────────────────────────────────────────

function refToResourceName($ref: string): string {
  // #/components/schemas/User → User
  // #/definitions/User → User
  const parts = $ref.split("/");
  return parts[parts.length - 1];
}

function openApiTypeToBackGen(type: string, format?: string): string {
  if (type === "integer" || type === "number") {
    if (format === "float" || format === "double") return "number";
    return "number";
  }
  if (type === "boolean") return "boolean";
  if (type === "string") {
    if (format === "date" || format === "date-time") return "date";
    return "string";
  }
  return "string";
}

function isReferenceSchema(schema: OpenAPISchema): boolean {
  // Simple reference like { "$ref": "#/components/schemas/User" }
  // or single allOf with $ref
  if (schema.$ref) return true;
  if (schema.allOf?.length === 1 && schema.allOf[0].$ref) return true;
  return false;
}

// ── Import Logic ───────────────────────────────────────────────

export interface ImportOpenApiOptions {
  output?: string;
}

/**
 * `backgen import openapi <file>`
 *
 * Parse an OpenAPI 3.x (or Swagger 2.0) spec, extract model schemas,
 * and output a backgen.yaml file.
 */
export async function importOpenApiCommand(
  specFile: string,
  options: ImportOpenApiOptions
): Promise<void> {
  console.log(chalk.blue.bold("\n🔌 BackGen - Import OpenAPI\n"));

  // Read spec file
  let raw: string;
  try {
    raw = await fs.readFile(specFile, "utf-8");
  } catch {
    console.error(chalk.red(`Error: Spec file not found: ${specFile}`));
    process.exit(1);
  }

  // Parse JSON or YAML
  let doc: OpenAPIDoc;
  if (specFile.endsWith(".json")) {
    try {
      doc = JSON.parse(raw) as OpenAPIDoc;
    } catch {
      console.error(chalk.red("Error: Invalid JSON spec."));
      process.exit(1);
    }
  } else {
    // Try YAML
    try {
      const jsyaml = await import("js-yaml");
      doc = jsyaml.load(raw) as OpenAPIDoc;
    } catch {
      console.error(chalk.red("Error: Invalid YAML spec."));
      process.exit(1);
    }
  }

  // Detect version
  const isV3 = !!doc.openapi;
  const schemas = isV3
    ? doc.components?.schemas
    : doc.definitions;

  if (!schemas || Object.keys(schemas).length === 0) {
    console.error(
      chalk.red(
        isV3
          ? "Error: No schemas found in components/schemas."
          : "Error: No definitions found (Swagger 2.0)."
      )
    );
    process.exit(1);
  }

  const resourceNames = Object.keys(schemas).filter(
    (name) => !name.startsWith("Error") && !name.startsWith("Response") && name !== "inline_response_200"
  );

  console.log(chalk.cyan(`Found ${resourceNames.length} model schema(s)\n`));

  // Detect relations between schemas (heuristic: $ref to another resource)
  const relationMap = new Map<string, string[]>();

  // Build YAML output
  let yamlOutput = `# Auto-generated by backgen import openapi\n`;
  yamlOutput += `# Source: ${path.basename(specFile)}\n`;

  if (doc.info) {
    yamlOutput += `# API: ${doc.info.title ?? "Untitled"} v${doc.info.version ?? "?"}\n`;
  }

  yamlOutput += `\nproject:\n`;
  yamlOutput += `  name: ${doc.info?.title?.toLowerCase().replace(/\s+/g, "-") ?? "my-api"}\n`;
  yamlOutput += `  framework: express\n`;
  yamlOutput += `  database: postgresql\n`;
  yamlOutput += `  orm: prisma\n\n`;

  // Detect references between resources for relation suggestions
  for (const name of resourceNames) {
    const schema = schemas[name];
    if (!schema?.properties) continue;
    const refs: string[] = [];
    for (const [, prop] of Object.entries(schema.properties)) {
      if (prop.$ref) {
        const target = refToResourceName(prop.$ref);
        if (resourceNames.includes(target)) refs.push(target);
      }
      if (prop.items?.$ref) {
        const target = refToResourceName(prop.items.$ref);
        if (resourceNames.includes(target)) refs.push(target + "[]");
      }
    }
    if (refs.length > 0) {
      relationMap.set(name, refs);
    }
  }

  yamlOutput += `plugins:\n`;
  yamlOutput += `  # - jwt\n`;
  yamlOutput += `  # - stripe\n\n`;

  yamlOutput += `resources:\n`;

  for (const name of resourceNames.sort()) {
    const schema = schemas[name];

    // Skip pure reference schemas (e.g. { $ref: "..." })
    if (isReferenceSchema(schema)) continue;

    yamlOutput += `  ${name}:\n`;
    yamlOutput += `    fields:\n`;

    if (schema?.properties) {
      for (const [propName, prop] of Object.entries(schema.properties)) {
        if (propName === "id" || propName.startsWith("_")) continue;
        if (prop.$ref) {
          // Reference field — add as relation
          const target = refToResourceName(prop.$ref);
          if (resourceNames.includes(target)) continue; // handled in relations
        }

        const fieldType = openApiTypeToBackGen(prop.type ?? "string", prop.format);
        yamlOutput += `      ${propName}: ${fieldType}\n`;
      }
    } else {
      // Fallback for schemas without properties
      yamlOutput += `      name: string\n`;
    }

    if (schema?.description) {
      yamlOutput += `    # ${schema.description}\n`;
    }

    // Add relations detected from $ref
    const refs = relationMap.get(name);
    if (refs && refs.length > 0) {
      yamlOutput += `    relations:\n`;
      for (const ref of refs) {
        if (ref.endsWith("[]")) {
          yamlOutput += `      ${ref.toLowerCase().replace("[]", "s")}: ${ref}\n`;
        } else {
          yamlOutput += `      ${ref.toLowerCase()}: ${ref}\n`;
        }
      }
    }

    yamlOutput += `    softDelete: false\n`;
  }

  // Write output
  const outputFile = options.output ?? "backgen.yaml";
  const outputPath = path.resolve(process.cwd(), outputFile);

  await fs.writeFile(outputPath, yamlOutput, "utf-8");

  console.log(chalk.green(`\n✨ ${outputFile} generated with ${resourceNames.length} resource(s)!\n`));
  console.log(chalk.cyan("Next step: backgen generate schema backgen.yaml"));
  if (!options.output) {
    console.log(chalk.gray("  (use --output to specify a different filename)\n"));
  }
}
